name: Deploy to Vercel
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19
          cache: "yarn"

      - name: Install and Build
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Install Latest Vercel CLI
        run: npm install --global vercel@latest

      # Vercel handles project creation automatically via CLI
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_DEPLOYMENT_TOKEN }}
          vercel-args: "--prod --yes"
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
